$(document).ready(function(){
    $("#product-img, .product-p").click(function(){
        $(".product-description").fadeToggle();
        $(".product").fadeToggle();
    });
    $("#design-img,.design-p").click(function(){
        $(".design-description").fadeToggle();
        $(".design").fadeToggle();
    });
    $("#dev-img,.dev-p").click(function(){
        $(".dev-description").fadeToggle();
        $(".dev").fadeToggle();
    });
    $("#project").hover(function(){
        $("#empty").slideDown("slow");
        $("#project").mouseout(function(){
            $("#empty").slideUp("slow");
        });
    });
    $("#project1").hover(function(){
        $("#pic1").slideDown("slow");
        $("#project2").mouseout(function(){
            $("#pic1").slideUp("slow");
        });
    });
});